spring:
  h2:
    console:
      enable: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:backofficeDb
    driver-class-name: org.h2.Driver
    username: root
    password: '1111'

  jpa:
    hibernate:
      ddl-auto: create-drop
    generatie-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

